import { Container, Grid } from "@mui/material";
import Head from "next/head";
import React, { useContext } from "react";

import { GlobalContext } from "../src/context/GlobalContext";
import CartCard from "../src/components/Cart/CartCard";
import { Product } from "../src/types/ProductTypes";

interface IProps {
  product: Product;
}

const Cart = () => {
  const { cart } = useContext(GlobalContext);
  return (
    <>
      <Head>
        <title>Rohlik Eshop Cart</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Container maxWidth="lg">
          <Grid container spacing={2}>
            {cart.map((product: any) => {
              return <CartCard key={product.id} product={product} />;
            })}
          </Grid>
        </Container>
      </main>
    </>
  );
};

export default Cart;
